"""Add solution code

Revision ID: df69af62d9a4
Revises: 736e93a32589
Create Date: 2023-08-22 20:21:30.762229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df69af62d9a4'
down_revision = '736e93a32589'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
